language: node_js
node_js:
- '0.12'
env:
- NODE_ENV=test
services: mongodb
before_script:
- NODE_ENV=test node bootstrap.js
- sleep 3
script:
- ./node_modules/.bin/mocha --compilers js:babel/register --timeout 10000 tests/backend/*.js
- ./node_modules/.bin/mocha-casperjs tests/frontend/*.js; exit 0
deploy:
  provider: heroku
  api_key:
    secure: EAuUrAUTb8b6WvLWk7d5WMNekzZNsUK8jl6vWiS+D2zNMGCWGCxHG5GpPAIe+IwYW0PRTI5s5L1OjdhZXRlbzrFOwg3NKzwM/Z5jzVSL4oG8QZmf9GYiulyrq574jRoxw2vynX4SxXGhDnNyQtrL3Yt3HubJTfD/32Rv5p61/KkaEJgn5nlW1RwjC3qvBr7WpjhibRgybGVBGEWcYe61jpqRqGlQeoQMMmZtlzBE19ET8Avglugo/90Htl7nDGGhcYB2Qmz9IFwyfi4OcfHkpJWtJkE6gsfvsuw/mo+t2SfB2R8qUZ/F29ADj99V2BbY0MU3wTUUF8VV1XsHN+opnEsmoXw1TOv02xriMIkuxPD+Kvbz2ZHvdgQu9eUn6Xtb7DLvjPA0MnJonebct+kOdCJk0Pd68Bni1eKFnEkORIrEBmm4fnsTe0W4XUekubiza14AEakcpSW3Oh2kU/3mzzmAtAaiMjDNxx7amMUAQ/AQimoCtNGIG5Jw1nle8lGzHmrOSjCW4NpYAKMXD4QnbSZyLIuGIPFbHb15UTTc4hoIR0anJb//rmDM2iXoBVAndeXnBAFVg7iFJo6tD8B1GB1ruPoiTi1tu8gqgnw58UNNOpCNOliZQYbnJosGnQ139o4IZAiG/XQcJhFke/UQ3HrsIB/6g4RG9WppkHWmB2k=
  app: klapec-todo-express
  on: production
