language: node_js
node_js:
- '0.12'
env:
- NODE_ENV=test
sudo: required
services: mongodb
before_script:
- npm install -g forever
- NODE_ENV=test forever start bootstrap.js
script:
- sleep 3
- ./node_modules/.bin/mocha --compilers js:babel/register --timeout 10000 tests/backend/*.js
- ./node_modules/.bin/mocha-casperjs tests/frontend/*.js; exit 0
deploy:
  provider: heroku
  app: klapec-todo-express
  api_key:
    secure: PYEohkNpEGSRVgfQDQU1z6BXDK6WNikvsC2Hxl/nfrMwXXsHnVpjJEZPLU+f0qhmZ//8SH2FLYCPZJzvE929cDfKTboXQzZRuBGBo1izZMel/t+TIchwVBk5PNtBMvIGNjy0UTVYgdtGPrIh91If4kRGnRzxTrtg36mpiMlmQEhvbss6HKhhSi/uVNswfTTUEndoRuzoz0Hp2ve0I0BvJi/HabkphKmo7dwiVi0nRlOQcdmwMD+v8XWFPCwz1m+rVNs7Un2W6F5SQCdSQ7/qIsmrErkur0lW0T+7/61ipH42AkOe1VvnJpHb3efRCiFomJJjCGaJeO+Tkzclho4S2xAdQ7/oYF3/EqV8vLTep1ubA3MQUIcyCQfQFmcaNJtOOm1U0i0KTTAFYnx4tcvEg3exuXHGYeWhXqQPHCyI1aAzn9u8kkaZ2iQBxD5KA1DFJIrAMGlbaYFk/KjzTXmNUAkqjAXzu64QEt7zz94XB5aFhHloOFd+aBGYK+5Ysgy2jscOmgdKcUut80q/+qGCh3nZH1T6qMHAZcCqOEbHgY2RiV4GnqtlQFOYjbIcenVI7D/7u3o8qBsfvpG8/naQ2/HIX/zsnxreLBuQPy0N+Zn4hvyjtI4yGc/nR4/y6vshp7TmR0mkbBr9z9/Og9U4+Ij9R+HbuKzZKihOOnk8ePQ=
