language: node_js
node_js:
- '0.12'
env:
- NODE_ENV=test
sudo: false
before_script:
- npm install -g forever
- forever start bootstrap.js
script:
- sleep 3
- ./node_modules/.bin/mocha --compilers js:babel/register --timeout 10000 tests/backend/*.js
- ./node_modules/.bin/mocha-casperjs tests/frontend/*.js; exit 0
