language: node_js
node_js:
  - '0.12'
env:
  - NODE_ENV=test
sudo: false
cache:
  directories:
    - node_modules
before_script:
  - node bootstrap.js
  - sleep 3
script:
  - ./node_modules/.bin/mocha --compilers js:babel/register --timeout 10000 tests/backend/*.js
  - ./node_modules/.bin/mocha-casperjs tests/frontend/*.js
