language: node_js
node_js:
- '0.12'
services:
- mongodb
env:
- NODE_ENV=test
sudo: false
cache:
  directories:
    - node_modules
before_script:
- ./node_modules/.bin/forever start bootstrap.js
script:
- sleep 3
- ./node_modules/.bin/mocha --compilers js:babel/register --timeout 10000 tests/backend/*.js
- ./node_modules/.bin/mocha-casperjs tests/frontend/*.js
